books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.page, name='page'),
    path('data/<str:searchKey>', views.data, name='data'),
]

faq/urls.py
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.page, name='page'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('tambah-kegiatan/', views.kegiatan, name='kegiatan'),
    path('tambah-peserta/<int:id>', views.peserta, name='peserta'),
]

story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('faq/',include('faq.urls')),
    path('books/',include('books.urls')),
]

books/models.py
from django.db import models

# Create your models here.

faq/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Peserta(models.Model):
    namaPeserta = models.CharField(max_length=100)
    class Meta:
        ordering = ['namaPeserta']


class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=100)
    peserta = models.ManyToManyField(Peserta)
    class Meta:
        ordering = ['namaKegiatan']

    def absolute_url(self):
        return reverse("main:peserta", kwargs = {"id" : self.id})

books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def page(request):
    return render(request, 'books/books.html')

def data(request,*args, **kwargs):
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + kwargs["searchKey"]
    r = requests.get(url_tujuan)

    buku = r.json()

    data_hasil = {
        "hasilBuku": [],
    }

    buku = buku["items"]


    for tiapBuku in buku:
        bukuKei = tiapBuku["volumeInfo"]
        bukuJson = {}

        bukuJson["foto"] = bukuKei["imageLinks"]["thumbnail"] if "imageLinks" in bukuKei.keys() else "https://image.freepik.com/free-photo/vertical-view-eiffel-tower-paris-france_1258-3169.jpg"
        bukuJson["judul"] = bukuKei["title"] 
        bukuJson["deskripsi"] = bukuKei["description"] if "description" in bukuKei.keys() else " "

        data_hasil["hasilBuku"].append(bukuJson)

    return JsonResponse(data_hasil, safe=False)

faq/views.py
from django.shortcuts import render

# Create your views here.
def page(request):
    return render(request, 'faq/faqq.html')

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Kegiatan, Peserta
from .form import FormKegiatan, FormPeserta, CreateUserForm
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def home(request):
    tkegiatan = Kegiatan.objects.all()
    context = {
        "kegiatan" : tkegiatan
    }
    return render(request, 'main/home.html', context)

def kegiatan(request):
    form = FormKegiatan()

    if request.method == "POST":
        form = FormKegiatan(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")

    context = {
        "form" : form,
    }
    return render(request, 'main/kegiatan.html', context)

def peserta(request, *args, **kwargs):
    form = FormPeserta()

    if request.method == "POST":
        namaPeserta = request.POST.get("namaPeserta")
        pesertaDaftar = Peserta.objects.create(namaPeserta = namaPeserta)
        kegiatan = Kegiatan.objects.get(id = kwargs["id"])
        kegiatan.peserta.add(pesertaDaftar)
        return redirect("/")
    
    
    context = {
        "form" : form,
    }

    return render(request, "main/peserta.html", context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username atau Password salah')
            return render(request, 'main/login.html')

    return render(request, 'main/login.html')

def logoutUser(request):
    logout(request)
    return redirect("/login/")

def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Akun telah dibuat untuk ' + user)
            return redirect("/login/")

    context = {'form':form}
    return render(request, 'main/register.html', context)

books/templates/books/books.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
  <title>Books</title>
{% endblock meta %}



{% block content %}
<h1 class="text-center">Books</h1>
<br><br>
<div class="container">
    <input id="keyword" placeholder="Masukkan kata kunci" class="form-control">
    <br><br>

    <table class="table borderless">
        <tbody id="hasil">
        </tbody>
      </table>

    <!-- <ol id="hasil">
        
    </ol> -->
</div>


<script src="{% static 'books/js/script.js' %}"></script>
{% endblock content %}
    
    

faq/templates/faq/faqq.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>FAQ</title>
  <link rel="stylesheet" href="{% static 'faq/css/style.css' %}"> 
  <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
{% endblock meta %}
    

{% block content %} 
<h1 class="text-center">FAQ</h1>
<div class="container">
  <br>
  <div class="row d-flex flex-column justify-content-center align-items-center">
      <div class="the-accordion col-md-12 p-0 shadow-lg bg-white rounded">
          <div class="section-1">
              <div class="head-accor d-flex justify-content-between p-2 rounded bg-info rounded-top text-white mt-1 border border-info">
                  <div class="label toggle m-0">
                      <h3 class="m-1">Apa aktivitas Sultan saat ini?</h3>
                  </div>
                  <div class="arrow d-flex flex-row justify-content-around">   
                    <h4 class="down"><i class="fa fa-chevron-down" aria-hidden="true"></i></h4>
                    <h4 class="up"><i class="fa fa-chevron-up" aria-hidden="true"></i></h4>
                  </div>
              </div>
              <div class="content-accor px-3 pt-1">
                  <p>Saat ini saya sedang kuliah di Fakultas Ilmu Komputer di Universitas Indonesia. Mata kuliah yang saya ambil semester ini yaitu, Perancangan dan pengembangan Web, Dasar-dasar Aksitektur Komputer, Struktur Data dan Algoritma dan lain-lain. Saya juga mengikuti beberapa kegiatan organisasi.</p>
              </div>
          </div>
          <div class="section-2">
              <div class="head-accor d-flex justify-content-between p-2 rounded bg-info rounded-top text-white mt-1 border border-info">
                  <div class="label toggle">
                      <h3 class="m-1">Pengalaman organisasi Sultan apa aja?</h3>
                  </div>
                  <div class="arrow d-flex flex-row justify-content-around">
                    <h4 class="down"><i class="fa fa-chevron-down" aria-hidden="true"></i></h4>
                    <h4 class="up"><i class="fa fa-chevron-up" aria-hidden="true"></i></h4>
                  </div>
              </div>
              <div class="content-accor px-3 pt-1">
                  <p>Saat ini saya mengikuti dua organisasi yaitu, DPM(Dewan Perwakilan Mahasiswa) dan FUKI(Forum Ukhuwah dan Kajian Islam). Di DPM saya menjadi anggota Pengawasan sedangkan di Fuki saya menjadi anggota Sosmas(Sosial dan Kemasyarakatan).</p>
              </div>
          </div>
          <div class="section-3">
              <div class="head-accor d-flex justify-content-between p-2 rounded bg-info rounded-top text-white mt-1 border border-info">
                  <div class="label toggle">
                      <h3 class="m-1" >Pengalaman Kepanitiaan Sultan apa aja?</h3>
                  </div>
                  <div class="arrow d-flex flex-row justify-content-around" >
                    <h4 class="down"><i class="fa fa-chevron-down" aria-hidden="true"></i></h4>
                    <h4 class="up"><i class="fa fa-chevron-up" aria-hidden="true"></i></h4>
                  </div>
              </div>
              <div class="content-accor px-3 pt-1">
                  <p>Saya sempat mengikuti satu kepanitiaan yaitu acara perlombaan keislaman yang didalamnya terdapat banyak lomba seperti lomba baca Al-qur'an, lomba menghafal Al-qur'an, dan lain-lain. Akan tetapi, saya belum sempat untuk mengikuti kepanitiaan yang ada di Fasilkom.</p>
              </div>
          </div>
          <div class="section-4">
              <div class="head-accor d-flex justify-content-between p-2 rounded bg-info rounded-top text-white mt-1 border border-info">
                  <div class="label toggle">
                      <h3 class="m-1">Apa saja prestasi Sultan yang pernah diraih?</h3>
                  </div>
                  <div class="arrow d-flex flex-row justify-content-around">
                    <h4 class="down"><i class="fa fa-chevron-down" aria-hidden="true"></i></h4>
                    <h4 class="up"><i class="fa fa-chevron-up" aria-hidden="true"></i></h4>
                  </div>
              </div>
              <div class="content-accor px-3 pt-1">
                  <p>Dulu saya pernah mendapat prestasi yang bersifat lokal di sekolah saya saja seperti lomba hadist dan lain-lain. Saya jarang mengikuti lomba-lomba. Akan tetapi, saya ada keinginan untuk mengikuti beberapa lomba saat berada di Fasilkom ini.</p>
              </div>
          </div>
      </div>
  </div>
</div>

<br><br><br><br><br><br>


  
  <script src="{% static 'faq/js/script.js' %}"></script>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Kegiatan</title>
{% endblock meta %}

{% block content %}
<h1 class="text-center">Daftar Kegiatanku</h1><br>
<div class="container">

  <div class="row">
    
    {% for k in kegiatan %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 card border-info mb-3">
        <div class="card-header bg-info">
          <h4 class="text-center">{{k.namaKegiatan}}</h4>
        </div>
        <div class="card-body">
          <h5>Peserta:</h5>
          <table class="table table-stripped table-borderless">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Nama</th>
              </tr>
            </thead>
            <tbody>
              {% for p in k.peserta.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{p.namaPeserta}}</td>
              </tr>
              {% endfor %}     
            </tbody>
          </table>
          {% if user.is_authenticated %}
            <a href="{{k.absolute_url}}" class="btn btn-success btn-block">Tambah</a>
          {% endif %}
        </div>
      </div>
    </div>  
    {% endfor %}
      
  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'main:kegiatan' %}" class="btn btn-success btn-block btn-lg">Tambah Kegiatan</a>
  {% endif %}
</div>
{% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1 class="text-center">Tambah Kegiatan</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="col-md-12">
                <input class="btn btn-success" type="submit" value="tambah kegiatan">
                <a href="{% url 'main:home' %}" class="btn btn-danger">Kembali</a>
            </div>
        </form>
    </div>
{% endblock content %}
    

main/templates/main/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #e8e6ed !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #17a2b8;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:hover{
			/* background-color: #0056b3 !important; */
			transform: scale(1.015);
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

        .sign{
            color: #33ccff;
        }

		#messages{
			text-align: center;
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		@media only screen and (max-width: 769px){
			.user_card{
				transform: scale(1.0);
			}
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %} 
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                
                
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
                    
                
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'main:register' %}" class="ml-2 sign">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

main/templates/main/peserta.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <h1 class="text-center">Tambah Peserta</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="col-md-12">
                <input class="btn btn-success" type="submit" value="tambah peserta">
                <a href="{% url 'main:home' %}" class="btn btn-danger">Kembali</a>
            </div>
        </form>
    </div>
{% endblock content %}
    

main/templates/main/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #e8e6ed !important;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #17a2b8;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:hover{
			/* background-color: #0056b3 !important; */
			transform: scale(1.015);
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

        .log{
            color: #33ccff;
        }

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		@media only screen and (max-width: 769px){
			.user_card{
				transform: scale(1.0);
			}
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %} 
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
                </div>
                
                {{form.errors}}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'main:login' %}" class="ml-2 log">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-info border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a class="navbar-brand text-white" href="{% url 'main:home' %}">Web</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-white text-left" href="{% url 'main:home' %}">Kegiatan</a>
      <a class="p-2 text-white" href="{% url 'faq:page' %}">FAQ</a>
      <a class="p-2 text-white" href="{% url 'books:page' %}">Books</a>
      {% if user.is_authenticated %}
        <a class="text-white mr-1"><span class="glyphicon glyphicon-user text-white mr-2"></span>Hallo, {{request.user}}</a>
        <a class="text-white" href="{% url 'main:logout' %}"><span class="glyphicon glyphicon-log-in text-white"></span> Logout</a>
      {% else %}
        <a class="text-white mr-1" href="{% url 'main:register' %}"><span class="glyphicon glyphicon-user text-white"></span> Sign Up</a>
        <a class="text-white" href="{% url 'main:login' %}"><span class="glyphicon glyphicon-log-in text-white"></span> Login</a>
      {% endif %}
    </nav>
  </div>
  {% block content %}
  {% endblock content %}
</body>

</html>